<#
.SYNOPSIS
    Invokes a single standalone OpenCode agent process for one task.

.DESCRIPTION
    Each task gets its own private OpenCode process via --standalone. The
    background service is never used, because that service does not expose a
    compatible V2 health response, so --server is explicitly refused.

    Complete stdout and stderr are captured to a timestamped file under
    .automation/logs. The OpenCode session id is extracted when the stream
    contains one, and the mandatory agent contract markers are parsed from the
    transcript.

.PARAMETER TaskId
    Roadmap task id, used in the prompt and in the log filename.

.PARAMETER Prompt
    The fully rendered agent prompt.

.PARAMETER PromptFile
    Optional path the prompt is also written to, so the exact instructions sent
    to the agent are auditable after the fact.

.PARAMETER Label
    'task' or 'recovery'. Only affects the log filename.

.OUTPUTS
    A PSCustomObject with SessionId, Status, TaskId, ExitCode, LogPath,
    Parsed, BadLines and TranscriptPath.
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$TaskId,
    [Parameter(Mandatory = $true)][string]$Prompt,
    [string]$PromptFile = '',
    [ValidateSet('task', 'recovery')]
    [string]$Label = 'task',
    # Continue a previous durable OpenCode session instead of starting a new
    # one. Verified working on OpenCode v2.0.11 with --standalone.
    [string]$ResumeSessionId = ''
)

Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'

. (Join-Path $PSScriptRoot 'Automation.Common.ps1')

$paths = Get-AutomationPaths
$config = Get-Config

# ---------------------------------------------------------------------------
# Refuse the unsupported server mode before anything is launched
# ---------------------------------------------------------------------------

foreach ($forbidden in $config.opencode.forbiddenFlags) {
    if ($Prompt -match [regex]::Escape($forbidden)) {
        throw "Refusing to invoke OpenCode: the prompt contains the forbidden flag '$forbidden'."
    }
}

if ($config.opencode.useBackgroundServer) {
    throw 'Config error: opencode.useBackgroundServer must be false for this project.'
}

# ---------------------------------------------------------------------------
# Resolve how OpenCode must actually be launched on this machine
# ---------------------------------------------------------------------------
#
# `Get-Command opencode` resolves to a .ps1 shim here, and Start-Process
# launches Win32 executables, so handing it that path fails with
# "%1 is not a valid Win32 application". Resolution and the launch prefix are
# resolved here, in a testable helper, rather than inline.

$resolution = Resolve-OpenCodeCommand -Command $config.opencode.command
$launch = Get-OpenCodeLaunchPrefix -Resolution $resolution

Write-AutomationLog "opencode resolved to $($resolution.ResolvedPath) [$($resolution.CommandType)] via $($resolution.LaunchMode)"
Write-AutomationLog "launch prefix: $($launch.Description)"

$openCodeArgs = @(Get-OpenCodeArgs -Config $config -TaskId $TaskId -Label $Label -Prompt $Prompt -ResumeSessionId $ResumeSessionId)

if ($ResumeSessionId) {
    Write-AutomationLog "attempting to continue OpenCode session $ResumeSessionId"
}

# Start-Process joins -ArgumentList into a single command-line string. That is
# acceptable for short tokens, but a multi-kilobyte multi-line prompt passed
# that way is fragile on Windows PowerShell 5.1. So the prompt is embedded in a
# generated launcher script as base64 and never appears on any command line; the
# launcher receives only its own path.
$promptBytes = [System.Text.Encoding]::UTF8.GetBytes($Prompt)
$promptBase64 = [System.Convert]::ToBase64String($promptBytes)

# The fixed OpenCode tokens are plain ASCII, so embedding them literally in the
# generated script is safe. Only the prompt needs base64.
$staticArgList = @($openCodeArgs[0..($openCodeArgs.Count - 2)]) |
    ForEach-Object { "'" + ($_ -replace "'", "''") + "'" }

$launcherPath = Join-Path $paths.Logs ("launcher-{0}-{1}-{2}.ps1" -f $TaskId, $Label, (Get-TimestampTag))

$launcherBody = @"
# Generated by scripts/automation/invoke-opencode.ps1. Transient helper, not a
# source file. It exists so the multi-line prompt is never placed on a command
# line, where Windows PowerShell 5.1 quoting is unreliable.
`$ErrorActionPreference = 'Continue'
`$target = '$($resolution.ResolvedPath)'
`$prompt = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('$promptBase64'))
`$ocArgs = @($($staticArgList -join ', '))
& `$target @ocArgs `$prompt
exit `$LASTEXITCODE
"@

[System.IO.File]::WriteAllText($launcherPath, $launcherBody, (New-Object System.Text.UTF8Encoding($true)))

# ---------------------------------------------------------------------------
# Capture a timestamped transcript
# ---------------------------------------------------------------------------

if (-not (Test-Path $paths.Logs)) { New-Item -ItemType Directory -Path $paths.Logs -Force | Out-Null }

$tag = Get-TimestampTag
$logPath = Join-Path $paths.Logs ("opencode-{0}-{1}-{2}.log" -f $TaskId, $Label, $tag)

if ($PromptFile) {
    $promptDir = Split-Path -Parent $PromptFile
    if (-not (Test-Path $promptDir)) { New-Item -ItemType Directory -Path $promptDir -Force | Out-Null }
    [System.IO.File]::WriteAllText($PromptFile, $Prompt, (New-Object System.Text.UTF8Encoding($false)))
}

Write-AutomationLog "opencode $Label for task $TaskId starting; log=$logPath"

Push-Location $paths.RepoRoot
try {
    $startTime = Get-Date

    # The generated launcher is the only thing executed. powershell.exe runs
    # it with -File, so Start-Process is never asked to run a .ps1 shim as a
    # Win32 application, and the only argument on the command line is the
    # launcher's own path, so the multi-line prompt never passes through
    # command-line quoting.
    #
    # Both streams go to files so the transcript does not have to fit in
    # memory, and the process is waited on synchronously.
    $proc = Start-Process -FilePath $launch.FilePath `
        -ArgumentList (@($launch.LeadingArgs) + @('-File', $launcherPath)) `
        -WorkingDirectory $paths.RepoRoot `
        -RedirectStandardOutput $logPath `
        -RedirectStandardError "$logPath.err" `
        -NoNewWindow `
        -PassThru

    # Windows PowerShell 5.1 only populates ExitCode if the process handle was
    # cached before the process ended. Touching .Handle once forces the object
    # to keep it, which is the documented workaround. Without this, ExitCode
    # comes back null and a genuinely successful agent gets recorded as a
    # failure.
    $null = $proc.Handle

    $null = $proc.WaitForExit()

    # An unknown exit code must never be read as success, so default to 1.
    $exitCode = $proc.ExitCode
    if ($null -eq $exitCode) {
        try { $null = $proc.Refresh(); $exitCode = $proc.ExitCode } catch { $exitCode = $null }
    }
    if ($null -eq $exitCode) {
        Write-AutomationLog 'opencode exit code was not reported by the process object; treating as 1' 'WARN'
        $exitCode = 1
    }

    $duration = [int]((Get-Date) - $startTime).TotalSeconds
}
finally {
    Pop-Location
    Remove-Item -Path $launcherPath -Force -ErrorAction SilentlyContinue
}

# Merge stderr into the primary transcript so marker parsing sees everything.
if (Test-Path "$logPath.err") {
    $errText = [System.IO.File]::ReadAllText("$logPath.err")
    if (-not [string]::IsNullOrWhiteSpace($errText)) {
        Add-Content -Path $logPath -Value "`n--- stderr ---`n$errText" -Encoding UTF8
    }
    Remove-Item "$logPath.err" -Force -ErrorAction SilentlyContinue
}

Write-AutomationLog "opencode $Label for task $TaskId exited with code $exitCode after ${duration}s"

# ---------------------------------------------------------------------------
# Parse the transcript
# ---------------------------------------------------------------------------

$parsed = ConvertFrom-OpenCodeJsonl -Path $logPath
$text = $parsed.Text

if ([string]::IsNullOrWhiteSpace($text)) {
    # JSONL parsing produced nothing usable. The raw transcript still contains
    # the agent's final message, and the contract marker must be recovered from
    # it rather than assumed absent.
    $text = Get-TextFromRawOutput -Path $logPath
    Write-AutomationLog 'jsonl text extraction was empty; fell back to raw transcript' 'WARN'
}

$markers = Get-TaskStatusMarker -Text $text

$sessionId = $parsed.SessionId
if (-not $sessionId) {
    # Some builds only expose the id in the raw text.
    $m = [regex]::Match($text, '(?i)session[\s"'':=_-]*id["'']?\s*[:=]\s*([A-Za-z0-9_-]{8,})')
    if ($m.Success) { $sessionId = $m.Groups[1].Value }
}

if (-not $sessionId -and $ResumeSessionId) {
    # A continuation that produced no events of its own still belongs to the
    # session we asked for.
    $sessionId = $ResumeSessionId
}

if ($sessionId) { Write-AutomationLog "opencode session id = $sessionId" }

$status = $markers.Status
if (-not $status) {
    # Missing marker is a FAILURE, never an implicit success.
    $status = 'FAIL'
    Write-AutomationLog 'agent contract marker AUTONOMOUS_TASK_STATUS was missing; treating as FAIL' 'WARN'
}
else {
    Write-AutomationLog "agent reported status $status for task $($markers.TaskId)"
}

# An agent that exits zero but reports FAIL still failed.
if ($exitCode -ne 0 -and $status -eq 'PASS') {
    Write-AutomationLog "agent reported PASS but process exit code was $exitCode; downgrading to FAIL" 'WARN'
    $status = 'FAIL'
}

# Did the requested session continuation actually attach? If not, the caller
# must fall back to a fresh session with a recovery prompt rather than treating
# this as a genuine task failure.
$resumeFailed = $false
if ($ResumeSessionId) {
    $resumeFailed = Test-SessionResumeFailed -Run ([pscustomobject]@{
            ExitCode  = $exitCode
            Text      = $text
            SessionId = $sessionId
        }) -ExpectedSessionId $ResumeSessionId

    if ($resumeFailed) {
        Write-AutomationLog "session resume of $ResumeSessionId did not attach; a fresh session with a recovery prompt is required" 'WARN'
    }
    else {
        Write-AutomationLog "session resume of $ResumeSessionId succeeded" 'INFO'
    }
}

# Preserve a human-readable transcript next to the raw log.
$transcriptPath = Join-Path $paths.Logs ("transcript-{0}-{1}-{2}.txt" -f $TaskId, $Label, $tag)
[System.IO.File]::WriteAllText($transcriptPath, $text, (New-Object System.Text.UTF8Encoding($false)))

return [pscustomobject]@{
    TaskId          = $TaskId
    Label           = $Label
    SessionId       = $sessionId
    Status          = $status
    MarkerTaskId    = $markers.TaskId
    MarkerFound     = $markers.MarkerFound
    ExitCode        = $exitCode
    DurationSeconds = $duration
    LogPath         = $logPath
    TranscriptPath  = $transcriptPath
    LaunchMode      = $resolution.LaunchMode
    ResolvedCommand = $resolution.ResolvedPath
    LaunchDescription = $launch.Description
    RequestedSessionId = $ResumeSessionId
    ResumeFailed    = $resumeFailed
    Parsed          = $parsed.Ok
    ParsedLines     = $parsed.ParsedLines
    BadLines        = $parsed.BadLines
    Text            = $text
}
